/* Automatically generated by
	VMPluginCodeGenerator VMMaker.oscog-eem.2498 uuid: f4233232-2c6b-452e-bdab-b814d48cc4a8
   from
	FilePlugin VMMaker.oscog-eem.2498 uuid: f4233232-2c6b-452e-bdab-b814d48cc4a8
 */
static char __buildInfo[] = "FilePlugin VMMaker.oscog-eem.2498 uuid: f4233232-2c6b-452e-bdab-b814d48cc4a8 " __DATE__ ;



#include "config.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* Default EXPORT macro that does nothing (see comment in sq.h): */
#define EXPORT(returnType) returnType

/* Do not include the entire sq.h file but just those parts needed. */
#include "sqConfig.h"			/* Configuration options */
#include "sqVirtualMachine.h"	/*  The virtual machine proxy definition */
#include "sqPlatformSpecific.h"	/* Platform specific definitions */

#define true 1
#define false 0
#define null 0  /* using 'null' because nil is predefined in Think C */
#ifdef SQUEAK_BUILTIN_PLUGIN
# undef EXPORT
# define EXPORT(returnType) static returnType
#endif

#include "FilePlugin.h"
#include "sqMemoryAccess.h"


/*** Constants ***/
#if !defined(COGMTVM) /* Allow this to be overridden on the compiler command line */
# define COGMTVM 0
#endif
#define DirBadPath 2
#define DirNoMoreEntries 1
#if !defined(PharoVM) /* Allow this to be overridden on the compiler command line */
# define PharoVM 0
#endif
#define PrimErrBadArgument 3
#define PrimErrBadIndex 4
#define PrimErrInappropriate 6
#define PrimErrNoMemory 9
#define PrimErrObjectMayMove 14
#define PrimErrUnsupported 7
#define PrimNoErr 0
#if !defined(SPURVM) /* Allow this to be overridden on the compiler command line */
# define SPURVM 1
#endif


/*** Function Prototypes ***/
static sqInt connectToFdwrite(int fd, sqInt writeFlag, struct foo * self);
static sqInt connectToFilewrite(void *cfile, sqInt writeFlag, struct foo * self);
EXPORT(sqInt) fileOpenNamesizewritesecure(char *nameIndex, sqInt nameSize, sqInt writeFlag, sqInt secureFlag, struct foo * self);
EXPORT(sqInt) fileOpenNewNamesizesecure(char *nameIndex, sqInt nameSize, sqInt secureFlag, struct foo * self);
extern usqIntptr_t fileRecordSize(struct foo * self);
extern SQFile * fileValueOf(sqInt objectPointer, struct foo * self);
EXPORT(const char*) getModuleName(void);
EXPORT(sqInt) initialiseModule(struct foo * self);
static sqInt makeDirEntryNamesizecreateDatemodDateisDirfileSize(char *entryName, sqInt entryNameSize, sqInt createDate, sqInt modifiedDate, sqInt dirFlag, squeakFileOffsetType fileSize, struct foo * self);
#if PharoVM
static sqInt makeDirEntryNamesizecreateDatemodDateisDirfileSizeposixPermissionsisSymlink(char *entryName, sqInt entryNameSize, sqInt createDate, sqInt modifiedDate, sqInt dirFlag, squeakFileOffsetType fileSize, sqInt posixPermissions, sqInt symlinkFlag, struct foo * self);
#endif /* PharoVM */
EXPORT(sqInt) moduleUnloaded(char *aModuleName, struct foo * self);
static void * pointerFrom(sqInt pointerByteArray, struct foo * self);
EXPORT(sqInt) primitiveConnectToFile(struct foo * self);
EXPORT(sqInt) primitiveConnectToFileDescriptor(struct foo * self);
EXPORT(sqInt) primitiveDirectoryCreate(struct foo * self);
EXPORT(sqInt) primitiveDirectoryDelete(struct foo * self);
EXPORT(sqInt) primitiveDirectoryDelimitor(struct foo * self);
EXPORT(sqInt) primitiveDirectoryEntry(struct foo * self);
EXPORT(sqInt) primitiveDirectoryGetMacTypeAndCreator(struct foo * self);
EXPORT(sqInt) primitiveDirectoryLookup(struct foo * self);
EXPORT(sqInt) primitiveDirectorySetMacTypeAndCreator(struct foo * self);
EXPORT(sqInt) primitiveDisableFileAccess(struct foo * self);
EXPORT(sqInt) primitiveFileAtEnd(struct foo * self);
EXPORT(sqInt) primitiveFileClose(struct foo * self);
EXPORT(sqInt) primitiveFileDelete(struct foo * self);
EXPORT(sqInt) primitiveFileDescriptorType(struct foo * self);
EXPORT(sqInt) primitiveFileFlush(struct foo * self);
EXPORT(sqInt) primitiveFileGetPosition(struct foo * self);
EXPORT(sqInt) primitiveFileOpen(struct foo * self);
EXPORT(sqInt) primitiveFileOpenNew(struct foo * self);
EXPORT(sqInt) primitiveFileRead(struct foo * self);
static sqInt primitiveFileReadWithoutPinning(struct foo * self);
static sqInt primitiveFileReadWithPinning(struct foo * self);
EXPORT(sqInt) primitiveFileRename(struct foo * self);
EXPORT(sqInt) primitiveFileSetPosition(struct foo * self);
EXPORT(sqInt) primitiveFileSize(struct foo * self);
EXPORT(sqInt) primitiveFileStdioHandles(struct foo * self);
EXPORT(sqInt) primitiveFileSync(struct foo * self);
EXPORT(sqInt) primitiveFileTruncate(struct foo * self);
EXPORT(sqInt) primitiveFileWrite(struct foo * self);
EXPORT(sqInt) primitiveHasFileAccess(struct foo * self);
EXPORT(sqInt) setInterpreter(struct VirtualMachine *anInterpreter);
EXPORT(sqInt) setMacFileTypeAndCreator(char *fileName, char *typeString, char *creatorString, struct foo * self);
EXPORT(sqInt) shutdownModule(struct foo * self);


/*** Variables ***/

#if !defined(SQUEAK_BUILTIN_PLUGIN)
static void * (*arrayValueOf)(sqInt oop, struct foo * self);
static sqInt (*booleanValueOf)(sqInt obj, struct foo * self);
static sqInt (*byteSizeOf)(sqInt oop, struct foo * self);
static sqInt (*characterObjectOf)(sqInt characterCode, struct foo * self);
static sqInt (*characterTable)(struct foo * self);
static sqInt (*classArray)(struct foo * self);
static sqInt (*classByteArray)(struct foo * self);
static sqInt (*classString)(struct foo * self);
static sqInt (*failed)(struct foo * self);
static sqInt (*falseObject)(struct foo * self);
static sqInt (*fetchPointerofObject)(sqInt index, sqInt oop, struct foo * self);
static void * (*firstIndexableField)(sqInt oop, struct foo * self);
static sqInt (*fullGC)(struct foo * self);
static sqInt (*instantiateClassindexableSize)(sqInt classPointer, sqInt size, struct foo * self);
static sqInt (*integerObjectOf)(sqInt value, struct foo * self);
static sqInt (*integerValueOf)(sqInt oop, struct foo * self);
static void * (*ioLoadFunctionFrom)(char *functionName, char *moduleName, struct foo * self);
static sqInt (*isKindOf)(sqInt oop, char *aString, struct foo * self);
static sqInt (*isBytes)(sqInt oop, struct foo * self);
static sqInt (*isIntegerObject)(sqInt objectPointer, struct foo * self);
static sqInt (*isWords)(sqInt oop, struct foo * self);
static sqInt (*isWordsOrBytes)(sqInt oop, struct foo * self);
static sqInt (*methodReturnBool)(sqInt boolean, struct foo * self);
static sqInt (*methodReturnInteger)(sqInt integer, struct foo * self);
static sqInt (*methodReturnValue)(sqInt oop, struct foo * self);
static sqInt (*nilObject)(struct foo * self);
static sqInt (*pop)(sqInt nItems, struct foo * self);
static sqInt (*popthenPush)(sqInt nItems, sqInt oop, struct foo * self);
static sqInt (*popRemappableOop)(struct foo * self);
static sqInt (*positive32BitIntegerFor)(unsigned int integerValue, struct foo * self);
static usqInt (*positive32BitValueOf)(sqInt oop, struct foo * self);
static sqInt (*positive64BitIntegerFor)(usqLong integerValue, struct foo * self);
static usqLong (*positive64BitValueOf)(sqInt oop, struct foo * self);
static usqIntptr_t (*positiveMachineIntegerValueOf)(sqInt oop, struct foo * self);
static sqInt (*primitiveFail)(struct foo * self);
static sqInt (*primitiveFailFor)(sqInt reasonCode, struct foo * self);
static sqInt (*primitiveFailForOSError)(sqLong osError, struct foo * self);
static sqInt (*primitiveFailureCode)(struct foo * self);
static sqInt (*pushRemappableOop)(sqInt oop, struct foo * self);
static sqInt (*slotSizeOf)(sqInt oop, struct foo * self);
static sqInt (*stSizeOf)(sqInt oop, struct foo * self);
static sqInt (*stackIntegerValue)(sqInt offset, struct foo * self);
static sqInt (*stackValue)(sqInt offset, struct foo * self);
static sqInt (*storePointerofObjectwithValue)(sqInt index, sqInt oop, sqInt valuePointer, struct foo * self);
static void (*tenuringIncrementalGC)(struct foo * self);
static sqInt (*topRemappableOop)(struct foo * self);
static sqInt (*trueObject)(struct foo * self);
#else /* !defined(SQUEAK_BUILTIN_PLUGIN) */
extern void * arrayValueOf(sqInt oop, struct foo * self);
extern sqInt booleanValueOf(sqInt obj, struct foo * self);
extern sqInt byteSizeOf(sqInt oop, struct foo * self);
#if VM_PROXY_MAJOR > 1 || (VM_PROXY_MAJOR == 1 && VM_PROXY_MINOR >= 13)
extern sqInt characterObjectOf(sqInt characterCode, struct foo * self);
#else
# define characterObjectOf(characterCode) 0
#endif
extern sqInt characterTable(struct foo * self);
extern sqInt classArray(struct foo * self);
extern sqInt classByteArray(struct foo * self);
extern sqInt classString(struct foo * self);
extern sqInt failed(struct foo * self);
extern sqInt falseObject(struct foo * self);
extern sqInt fetchPointerofObject(sqInt index, sqInt oop, struct foo * self);
extern void * firstIndexableField(sqInt oop, struct foo * self);
extern sqInt fullGC(struct foo * self);
extern sqInt instantiateClassindexableSize(sqInt classPointer, sqInt size, struct foo * self);
extern sqInt integerObjectOf(sqInt value, struct foo * self);
extern sqInt integerValueOf(sqInt oop, struct foo * self);
extern void * ioLoadFunctionFrom(char *functionName, char *moduleName, struct foo * self);
extern sqInt isKindOf(sqInt oop, char *aString, struct foo * self);
extern sqInt isBytes(sqInt oop, struct foo * self);
#if !defined(isIntegerObject)
extern sqInt isIntegerObject(sqInt objectPointer, struct foo * self);
#endif
extern sqInt isWords(sqInt oop, struct foo * self);
extern sqInt isWordsOrBytes(sqInt oop, struct foo * self);
extern sqInt methodReturnBool(sqInt boolean, struct foo * self);
extern sqInt methodReturnInteger(sqInt integer, struct foo * self);
extern sqInt methodReturnValue(sqInt oop, struct foo * self);
extern sqInt nilObject(struct foo * self);
extern sqInt pop(sqInt nItems, struct foo * self);
extern sqInt popthenPush(sqInt nItems, sqInt oop, struct foo * self);
extern sqInt popRemappableOop(struct foo * self);
extern sqInt positive32BitIntegerFor(unsigned int integerValue, struct foo * self);
extern usqInt positive32BitValueOf(sqInt oop, struct foo * self);
extern sqInt positive64BitIntegerFor(usqLong integerValue, struct foo * self);
extern usqLong positive64BitValueOf(sqInt oop, struct foo * self);
extern usqIntptr_t positiveMachineIntegerValueOf(sqInt oop, struct foo * self);
extern sqInt primitiveFail(struct foo * self);
extern sqInt primitiveFailFor(sqInt reasonCode, struct foo * self);
#if VM_PROXY_MAJOR > 1 || (VM_PROXY_MAJOR == 1 && VM_PROXY_MINOR >= 14)
extern sqInt primitiveFailForOSError(sqLong osError, struct foo * self);
#else
# define primitiveFailForOSError(osError) 0
#endif
extern sqInt primitiveFailureCode(struct foo * self);
extern sqInt pushRemappableOop(sqInt oop, struct foo * self);
extern sqInt slotSizeOf(sqInt oop, struct foo * self);
extern sqInt stSizeOf(sqInt oop, struct foo * self);
extern sqInt stackIntegerValue(sqInt offset, struct foo * self);
extern sqInt stackValue(sqInt offset, struct foo * self);
extern sqInt storePointerofObjectwithValue(sqInt index, sqInt oop, sqInt valuePointer, struct foo * self);
extern void tenuringIncrementalGC(struct foo * self);
extern sqInt topRemappableOop(struct foo * self);
extern sqInt trueObject(struct foo * self);
extern
#endif
struct VirtualMachine* interpreterProxy;
static const char *moduleName =
#ifdef SQUEAK_BUILTIN_PLUGIN
	"FilePlugin VMMaker.oscog-eem.2498 (i)"
#else
	"FilePlugin VMMaker.oscog-eem.2498 (e)"
#endif
;
static void * sCCPfn;
static void * sCDFfn;
static void * sCDPfn;
static void * sCGFTfn;
static void * sCLPfn;
static void * sCOFfn;
static void * sCRFfn;
static void * sCSFTfn;
static void * sDFAfn;
static void * sHFAfn;



/*	Connect to the supplied file descriptor. Answer the file oop.
	On POSIX platforms this translates to fdopen().
	writeFlag must be compatible with the existing file access. */

	/* FilePlugin>>#connectToFd:write: */
static sqInt
connectToFdwrite(int fd, sqInt writeFlag, struct foo * self)
{
    SQFile *file;
    sqInt fileOop;

	fileOop = instantiateClassindexableSize(classByteArray(self), sizeof(SQFile), self);
	/* begin fileValueOf: */
	if (!((isBytes(fileOop, self))
		 && ((byteSizeOf(fileOop, self)) == (sizeof(SQFile))))) {
		primitiveFail(self);
		file = null;
		goto l1;
	}
	file = firstIndexableField(fileOop, self);
	l1:	/* end fileValueOf: */;
	if (!(failed(self))) {
		sqConnectToFileDescriptor(file, fd, writeFlag, self);
	}
	return fileOop;
}


/*	Open the FILE* as file. Answer the file oop.
	writeFlag must be compatible with the existing file access. */

	/* FilePlugin>>#connectToFile:write: */
static sqInt
connectToFilewrite(void *cfile, sqInt writeFlag, struct foo * self)
{
    SQFile *file;
    sqInt fileOop;

	fileOop = instantiateClassindexableSize(classByteArray(self), sizeof(SQFile), self);
	/* begin fileValueOf: */
	if (!((isBytes(fileOop, self))
		 && ((byteSizeOf(fileOop, self)) == (sizeof(SQFile))))) {
		primitiveFail(self);
		file = null;
		goto l1;
	}
	file = firstIndexableField(fileOop, self);
	l1:	/* end fileValueOf: */;
	if (!(failed(self))) {
		sqConnectToFile(file, cfile, writeFlag, self);
	}
	return fileOop;
}


/*	Open the named file, possibly checking security. Answer the file oop. */

	/* FilePlugin>>#fileOpenName:size:write:secure: */
EXPORT(sqInt)
fileOpenNamesizewritesecure(char *nameIndex, sqInt nameSize, sqInt writeFlag, sqInt secureFlag, struct foo * self)
{
    SQFile *file;
    sqInt fileOop;
    sqInt okToOpen;

	fileOop = instantiateClassindexableSize(classByteArray(self), sizeof(SQFile), self);
	/* begin fileValueOf: */
	if (!((isBytes(fileOop, self))
		 && ((byteSizeOf(fileOop, self)) == (sizeof(SQFile))))) {
		primitiveFail(self);
		file = null;
		goto l1;
	}
	file = firstIndexableField(fileOop, self);
	l1:	/* end fileValueOf: */;
	if (!(failed(self))) {
		if (secureFlag) {

			/* If the security plugin can be loaded, use it to check for permission.
			   If not, assume it's ok */
			if (sCOFfn != 0) {
				okToOpen = ((sqInt (*) (char *, sqInt, sqInt)) sCOFfn)(nameIndex, nameSize, writeFlag);
				if (!okToOpen) {
					primitiveFail(self);
				}
			}
		}
	}
	if (!(failed(self))) {
		sqFileOpen(file, nameIndex, nameSize, writeFlag, self);
	}
	return fileOop;
}


/*	Open the new named file, possibly checking security. Answer the file oop. */

	/* FilePlugin>>#fileOpenNewName:size:secure: */
EXPORT(sqInt)
fileOpenNewNamesizesecure(char *nameIndex, sqInt nameSize, sqInt secureFlag, struct foo * self)
{
    sqInt exists;
    SQFile *file;
    sqInt fileOop;
    sqInt okToOpen;

	fileOop = instantiateClassindexableSize(classByteArray(self), sizeof(SQFile), self);
	/* begin fileValueOf: */
	if (!((isBytes(fileOop, self))
		 && ((byteSizeOf(fileOop, self)) == (sizeof(SQFile))))) {
		primitiveFail(self);
		file = null;
		goto l1;
	}
	file = firstIndexableField(fileOop, self);
	l1:	/* end fileValueOf: */;
	if (!(failed(self))) {
		if (secureFlag) {

			/* If the security plugin can be loaded, use it to check for permission.
			   If not, assume it's ok */
			if (sCOFfn != 0) {
				okToOpen = ((sqInt (*) (char *, sqInt, sqInt)) sCOFfn)(nameIndex, nameSize, true);
				if (!okToOpen) {
					primitiveFail(self);
				}
			}
		}
	}
	if (!(failed(self))) {
		exists = 0;
		sqFileOpenNew(file, nameIndex, nameSize, &exists, self);
		if ((failed(self))
		 && (exists)) {
			primitiveFailFor(PrimErrInappropriate, self);
		}
	}
	return fileOop;
}


/*	Return the size of a Smalltalk file record in bytes. */

	/* FilePlugin>>#fileRecordSize */
usqIntptr_t
fileRecordSize(struct foo * self)
{
	return sizeof(SQFile);
}


/*	Return a pointer to the first byte of of the file record within the given
	Smalltalk object, or nil if objectPointer is not a file record.
 */

	/* FilePlugin>>#fileValueOf: */
SQFile *
fileValueOf(sqInt objectPointer, struct foo * self)
{
	if (!((isBytes(objectPointer, self))
		 && ((byteSizeOf(objectPointer, self)) == (sizeof(SQFile))))) {
		primitiveFail(self);
		return null;
	}
	return firstIndexableField(objectPointer, self);
}


/*	Note: This is hardcoded so it can be run from Squeak.
	The module name is used for validating a module *after*
	it is loaded to check if it does really contain the module
	we're thinking it contains. This is important! */

	/* InterpreterPlugin>>#getModuleName */
EXPORT(const char*)
getModuleName(void)
{
	return moduleName;
}

	/* FilePlugin>>#initialiseModule */
EXPORT(sqInt)
initialiseModule(struct foo * self)
{
	sCCPfn = ioLoadFunctionFrom("secCanCreatePathOfSize", "SecurityPlugin", self);
	sCDPfn = ioLoadFunctionFrom("secCanDeletePathOfSize", "SecurityPlugin", self);
	sCGFTfn = ioLoadFunctionFrom("secCanGetFileTypeOfSize", "SecurityPlugin", self);
	sCLPfn = ioLoadFunctionFrom("secCanListPathOfSize", "SecurityPlugin", self);
	sCSFTfn = ioLoadFunctionFrom("secCanSetFileTypeOfSize", "SecurityPlugin", self);
	sDFAfn = ioLoadFunctionFrom("secDisableFileAccess", "SecurityPlugin", self);
	sCDFfn = ioLoadFunctionFrom("secCanDeleteFileOfSize", "SecurityPlugin", self);
	sCOFfn = ioLoadFunctionFrom("secCanOpenFileOfSizeWritable", "SecurityPlugin", self);
	sCRFfn = ioLoadFunctionFrom("secCanRenameFileOfSize", "SecurityPlugin", self);
	sHFAfn = ioLoadFunctionFrom("secHasFileAccess", "SecurityPlugin", self);
	return sqFileInit(self);
}

	/* FilePlugin>>#makeDirEntryName:size:createDate:modDate:isDir:fileSize: */
static sqInt
makeDirEntryNamesizecreateDatemodDateisDirfileSize(char *entryName, sqInt entryNameSize, sqInt createDate, sqInt modifiedDate, sqInt dirFlag, squeakFileOffsetType fileSize, struct foo * self)
{
    sqInt createDateOop;
    sqInt fileSizeOop;
    sqInt i;
    sqInt modDateOop;
    sqInt nameString;
    sqInt results;
    char *stringPtr;


	/* allocate storage for results, remapping newly allocated
	   oops if required in case GC happens during allocation */
	results = instantiateClassindexableSize(classArray(self), 5, self);
	
#if SPURVM
	nameString = instantiateClassindexableSize(classString(self), entryNameSize, self);
	createDateOop = positive32BitIntegerFor(createDate, self);
	modDateOop = positive32BitIntegerFor(modifiedDate, self);
	fileSizeOop = positive64BitIntegerFor(fileSize, self);

#else /* SPURVM */
	pushRemappableOop(results, self);
	nameString = instantiateClassindexableSize(classString(self), entryNameSize, self);
		pushRemappableOop(nameString, self);
	createDateOop = positive32BitIntegerFor(createDate, self);
		pushRemappableOop(createDateOop, self);
	modDateOop = positive32BitIntegerFor(modifiedDate, self);
		pushRemappableOop(modDateOop, self);
	fileSizeOop = positive64BitIntegerFor(fileSize, self);
	modDateOop = popRemappableOop(self);
	createDateOop = popRemappableOop(self);
	nameString = popRemappableOop(self);
	results = popRemappableOop(self)
#endif /* SPURVM */
;
	stringPtr = firstIndexableField(nameString, self);
	for (i = 0; i < entryNameSize; i += 1) {
		stringPtr[i] = (entryName[i]);
	}
	storePointerofObjectwithValue(0, results, nameString, self);
	storePointerofObjectwithValue(1, results, createDateOop, self);
	storePointerofObjectwithValue(2, results, modDateOop, self);
	storePointerofObjectwithValue(3, results, (dirFlag
		? trueObject(self)
		: falseObject(self)), self);
	storePointerofObjectwithValue(4, results, fileSizeOop, self);
	return results;
}

	/* FilePlugin>>#makeDirEntryName:size:createDate:modDate:isDir:fileSize:posixPermissions:isSymlink: */
#if PharoVM
static sqInt
makeDirEntryNamesizecreateDatemodDateisDirfileSizeposixPermissionsisSymlink(char *entryName, sqInt entryNameSize, sqInt createDate, sqInt modifiedDate, sqInt dirFlag, squeakFileOffsetType fileSize, sqInt posixPermissions, sqInt symlinkFlag, struct foo * self)
{
    sqInt createDateOop;
    sqInt fileSizeOop;
    sqInt i;
    sqInt modDateOop;
    sqInt nameString;
    sqInt posixPermissionsOop;
    sqInt results;
    char *stringPtr;


	/* allocate storage for results, remapping newly allocated
	   oops if required in case GC happens during allocation */
	results = instantiateClassindexableSize(classArray(self), 7, self);
	
#if SPURVM
	nameString = instantiateClassindexableSize(classString(self), entryNameSize, self);
	createDateOop = positive32BitIntegerFor(createDate, self);
	modDateOop = positive32BitIntegerFor(modifiedDate, self);
	fileSizeOop = positive64BitIntegerFor(fileSize, self);
	posixPermissionsOop = positive32BitIntegerFor(posixPermissions, self);

#else /* SPURVM */
	pushRemappableOop(results, self);
	nameString = instantiateClassindexableSize(classString(self), entryNameSize, self);
		pushRemappableOop(nameString, self);
	createDateOop = positive32BitIntegerFor(createDate, self);
		pushRemappableOop(createDateOop, self);
	modDateOop = positive32BitIntegerFor(modifiedDate, self);
		pushRemappableOop(modDateOop, self);
	fileSizeOop = positive64BitIntegerFor(fileSize, self);
		pushRemappableOop(fileSizeOop, self);
	posixPermissionsOop = positive32BitIntegerFor(posixPermissions, self);
	fileSizeOop = popRemappableOop(self);
	modDateOop = popRemappableOop(self);
	createDateOop = popRemappableOop(self);
	nameString = popRemappableOop(self);
	results = popRemappableOop(self)
#endif /* SPURVM */
;
	stringPtr = firstIndexableField(nameString, self);
	for (i = 0; i < entryNameSize; i += 1) {
		stringPtr[i] = (entryName[i]);
	}
	storePointerofObjectwithValue(0, results, nameString, self);
	storePointerofObjectwithValue(1, results, createDateOop, self);
	storePointerofObjectwithValue(2, results, modDateOop, self);
	storePointerofObjectwithValue(3, results, (dirFlag
		? trueObject(self)
		: falseObject(self)), self);
	storePointerofObjectwithValue(4, results, fileSizeOop, self);
	storePointerofObjectwithValue(5, results, posixPermissionsOop, self);
	storePointerofObjectwithValue(6, results, (symlinkFlag
		? trueObject(self)
		: falseObject(self)), self);
	return results;
}
#endif /* PharoVM */


/*	The module with the given name was just unloaded.
	Make sure we have no dangling references. */

	/* FilePlugin>>#moduleUnloaded: */
EXPORT(sqInt)
moduleUnloaded(char *aModuleName, struct foo * self)
{
	if ((strcmp(aModuleName, "SecurityPlugin")) == 0) {

		/* The security plugin just shut down. How odd. */
		sCCPfn = (sCDPfn = (sCGFTfn = (sCLPfn = (sCSFTfn = (sDFAfn = (sCDFfn = (sCOFfn = (sCRFfn = (sHFAfn = 0)))))))));
	}
	return 0;
}


/*	Answer the machine address contained in anExternalAddressOop. */

	/* FilePlugin>>#pointerFrom: */
static void *
pointerFrom(sqInt pointerByteArray, struct foo * self)
{
    union {void *address; unsigned char bytes[sizeof(void *)];} addressUnion;
    sqInt idx;
    unsigned char *ptr;

	if (!((isKindOf(pointerByteArray, "ByteArray", self))
		 && ((stSizeOf(pointerByteArray, self)) == (sizeof(void *))))) {
		return primitiveFailFor(PrimErrBadArgument, self);
	}
	ptr = arrayValueOf(pointerByteArray, self);
	if (failed(self)) {
		return null;
	}
	idx = 0;
	while (idx < (sizeof(void *))) {
		addressUnion.bytes[idx] = ptr[idx];
		idx += 1;
	}
	return addressUnion.address;
}


/*	Connect to the file with the supplied FILE* and writeFlag.
	FILE* must be supplied in a byte object (ByteArray) with the platform
	address size.
	writeFlag must be a boolean and compatible with the existing file access.
 */

	/* FilePlugin>>#primitiveConnectToFile */
EXPORT(sqInt)
primitiveConnectToFile(struct foo * self)
{
    void *cfile;
    sqInt cfileOop;
    SQFile *file;
    sqInt fileOop;
    sqInt filePointer;
    sqInt writeFlag;

	writeFlag = booleanValueOf(stackValue(0, self), self);
	cfileOop = stackValue(1, self);
	cfile = pointerFrom(cfileOop, self);
	if (failed(self)) {

		/* Ensure that the appropriate failure code has been set */
		return primitiveFailFor(PrimErrBadArgument, self);
	}
	/* begin connectToFile:write: */
	fileOop = instantiateClassindexableSize(classByteArray(self), sizeof(SQFile), self);
	/* begin fileValueOf: */
	if (!((isBytes(fileOop, self))
		 && ((byteSizeOf(fileOop, self)) == (sizeof(SQFile))))) {
		primitiveFail(self);
		file = null;
		goto l1;
	}
	file = firstIndexableField(fileOop, self);
	l1:	/* end fileValueOf: */;
	if (!(failed(self))) {
		sqConnectToFile(file, cfile, writeFlag, self);
	}
	filePointer = fileOop;
	if (!(failed(self))) {
		methodReturnValue(filePointer, self);
	}
	return 0;
}


/*	Connect to the existing file identified by fileDescriptor.
	fileDescriptor must be an integer.
	writeFlag is aboolean indicating whether to open in read or write mode and
	must be compatible with the existing file access.
 */

	/* FilePlugin>>#primitiveConnectToFileDescriptor */
EXPORT(sqInt)
primitiveConnectToFileDescriptor(struct foo * self)
{
    int fd;
    sqInt fdPointer;
    SQFile *file;
    sqInt fileOop;
    sqInt filePointer;
    sqInt writeFlag;

	writeFlag = booleanValueOf(stackValue(0, self), self);
	fdPointer = stackValue(1, self);
	if (!(isIntegerObject(fdPointer, self))) {
		return primitiveFailFor(PrimErrBadArgument, self);
	}
	fd = integerValueOf(fdPointer, self);
	if (failed(self)) {

		/* Ensure that the appropriate failure code has been set */
		return primitiveFailFor(PrimErrBadArgument, self);
	}
	/* begin connectToFd:write: */
	fileOop = instantiateClassindexableSize(classByteArray(self), sizeof(SQFile), self);
	/* begin fileValueOf: */
	if (!((isBytes(fileOop, self))
		 && ((byteSizeOf(fileOop, self)) == (sizeof(SQFile))))) {
		primitiveFail(self);
		file = null;
		goto l1;
	}
	file = firstIndexableField(fileOop, self);
	l1:	/* end fileValueOf: */;
	if (!(failed(self))) {
		sqConnectToFileDescriptor(file, fd, writeFlag, self);
	}
	filePointer = fileOop;
	if (!(failed(self))) {
		methodReturnValue(filePointer, self);
	}
	return 0;
}

	/* FilePlugin>>#primitiveDirectoryCreate */
EXPORT(sqInt)
primitiveDirectoryCreate(struct foo * self)
{
    sqInt dirName;
    char *dirNameIndex;
    sqInt dirNameSize;
    sqInt okToCreate;

	dirName = stackValue(0, self);
	if (!(isBytes(dirName, self))) {
		return primitiveFail(self);
	}
	dirNameIndex = firstIndexableField(dirName, self);

	/* If the security plugin can be loaded, use it to check for permission.
	   If not, assume it's ok */
	dirNameSize = byteSizeOf(dirName, self);
	if (sCCPfn != 0) {
		okToCreate =  ((sqInt (*)(char *, sqInt))sCCPfn)(dirNameIndex, dirNameSize);
		if (!okToCreate) {
			return primitiveFail(self);
		}
	}
	if (!(dir_Create(dirNameIndex, dirNameSize))) {
		return primitiveFail(self);
	}
	pop(1, self);
	return 0;
}

	/* FilePlugin>>#primitiveDirectoryDelete */
EXPORT(sqInt)
primitiveDirectoryDelete(struct foo * self)
{
    sqInt dirName;
    char *dirNameIndex;
    sqInt dirNameSize;
    sqInt okToDelete;

	dirName = stackValue(0, self);
	if (!(isBytes(dirName, self))) {
		return primitiveFail(self);
	}
	dirNameIndex = firstIndexableField(dirName, self);

	/* If the security plugin can be loaded, use it to check for permission.
	   If not, assume it's ok */
	dirNameSize = byteSizeOf(dirName, self);
	if (sCDPfn != 0) {
		okToDelete =  ((sqInt (*)(char *, sqInt))sCDPfn)(dirNameIndex, dirNameSize);
		if (!okToDelete) {
			return primitiveFail(self);
		}
	}
	if (!(dir_Delete(dirNameIndex, dirNameSize))) {
		return primitiveFail(self);
	}
	pop(1, self);
	return 0;
}

	/* FilePlugin>>#primitiveDirectoryDelimitor */
EXPORT(sqInt)
primitiveDirectoryDelimitor(struct foo * self)
{
    sqInt ascii;

	if ((interpreterProxy->minorVersion()) >= 13) {
		popthenPush(1, characterObjectOf(dir_Delimitor(), self), self);
	}
	else {
		ascii = dir_Delimitor();
		if ((ascii >= 0)
		 && (ascii <= 0xFF)) {
			popthenPush(1, fetchPointerofObject(ascii, characterTable(self), self), self);
		}
		else {
			primitiveFail(self);
		}
	}
	return 0;
}


/*	Two arguments - directory path, and simple file name;
	returns an array (see primitiveDirectoryLookup) describing the file or
	directory, or nil if it does not exist. 
	Primitive fails if the outer path does not identify a readable directory.
	(This is a lookup-by-name variant of primitiveDirectoryLookup.) */

	/* FilePlugin>>#primitiveDirectoryEntry */
EXPORT(sqInt)
primitiveDirectoryEntry(struct foo * self)
{
    sqInt createDate;
    sqInt dirFlag;
    char entryName[256];
    sqInt entryNameSize;
    squeakFileOffsetType fileSize;
    sqInt modifiedDate;
    sqInt okToList;
    sqInt pathName;
    char *pathNameIndex;
    sqInt pathNameSize;
    sqInt posixPermissions;
    char *reqNameIndex;
    sqInt reqNameSize;
    sqInt requestedName;
    sqInt status;
    sqInt symlinkFlag;
    sqInt v;

	createDate = 0;
	dirFlag = 0;
	entryNameSize = 0;
	modifiedDate = 0;
	posixPermissions = 0;
	symlinkFlag = 0;
	v = 0;
	requestedName = stackValue(0, self);
	pathName = stackValue(1, self);
	if (!(isBytes(pathName, self))) {
		return primitiveFail(self);
	}
	pathNameIndex = firstIndexableField(pathName, self);
	pathNameSize = byteSizeOf(pathName, self);
	reqNameIndex = firstIndexableField(requestedName, self);
	reqNameSize = byteSizeOf(requestedName, self);
	okToList = (sCLPfn != 0
		? ((sqInt (*)(char *, sqInt))sCLPfn)(pathNameIndex, pathNameSize)
		: 1);
	status = (okToList
		? dir_EntryLookup(pathNameIndex, pathNameSize, reqNameIndex, reqNameSize, entryName, (&entryNameSize), (&createDate), (&modifiedDate), (&dirFlag), (&fileSize), (&posixPermissions), (&symlinkFlag))
		: DirNoMoreEntries);
	if (failed(self)) {
		return null;
	}
	if (status == DirNoMoreEntries) {

		/* no entry; return nil */
		/* pop pathName, index, rcvr */
		popthenPush(3, nilObject(self), self);
		return null;
	}
	if (status == DirBadPath) {
		return primitiveFail(self);
	}
	popthenPush(3, 
#  if PharoVM
		makeDirEntryNamesizecreateDatemodDateisDirfileSizeposixPermissionsisSymlink(entryName, entryNameSize, createDate, modifiedDate, dirFlag, fileSize, posixPermissions, symlinkFlag, self)
#  else /* PharoVM */
		makeDirEntryNamesizecreateDatemodDateisDirfileSize(entryName, entryNameSize, createDate, modifiedDate, dirFlag, fileSize, self)
#  endif /* PharoVM */
		, self);
	return 0;
}

	/* FilePlugin>>#primitiveDirectoryGetMacTypeAndCreator */
EXPORT(sqInt)
primitiveDirectoryGetMacTypeAndCreator(struct foo * self)
{
    sqInt creatorString;
    char *creatorStringIndex;
    sqInt fileName;
    char *fileNameIndex;
    sqInt fileNameSize;
    sqInt okToGet;
    sqInt typeString;
    char *typeStringIndex;

	creatorString = stackValue(0, self);
	typeString = stackValue(1, self);
	fileName = stackValue(2, self);
	if (!((isBytes(creatorString, self))
		 && ((byteSizeOf(creatorString, self)) == 4))) {
		return primitiveFail(self);
	}
	if (!((isBytes(typeString, self))
		 && ((byteSizeOf(typeString, self)) == 4))) {
		return primitiveFail(self);
	}
	if (!(isBytes(fileName, self))) {
		return primitiveFail(self);
	}
	creatorStringIndex = firstIndexableField(creatorString, self);
	typeStringIndex = firstIndexableField(typeString, self);
	fileNameIndex = firstIndexableField(fileName, self);

	/* If the security plugin can be loaded, use it to check for permission.
	   If not, assume it's ok */
	fileNameSize = byteSizeOf(fileName, self);
	if (sCGFTfn != 0) {
		okToGet =  ((sqInt (*)(char *, sqInt))sCGFTfn)(fileNameIndex, fileNameSize);
		if (!okToGet) {
			return primitiveFail(self);
		}
	}
	if (!(dir_GetMacFileTypeAndCreator(fileNameIndex, fileNameSize, typeStringIndex, creatorStringIndex))) {
		return primitiveFail(self);
	}
	pop(3, self);
	return 0;
}

	/* FilePlugin>>#primitiveDirectoryLookup */
EXPORT(sqInt)
primitiveDirectoryLookup(struct foo * self)
{
    sqInt createDate;
    sqInt dirFlag;
    char entryName[256];
    sqInt entryNameSize;
    squeakFileOffsetType fileSize;
    sqInt index;
    sqInt modifiedDate;
    sqInt okToList;
    sqInt pathName;
    char *pathNameIndex;
    sqInt pathNameSize;
    sqInt posixPermissions;
    sqInt status;
    sqInt symlinkFlag;
    sqInt v;

	createDate = 0;
	dirFlag = 0;
	entryNameSize = 0;
	modifiedDate = 0;
	posixPermissions = 0;
	symlinkFlag = 0;
	v = 0;
	index = stackIntegerValue(0, self);
	pathName = stackValue(1, self);
	if (!(isBytes(pathName, self))) {
		return primitiveFail(self);
	}
	pathNameIndex = firstIndexableField(pathName, self);
	pathNameSize = byteSizeOf(pathName, self);
	okToList = (sCLPfn != 0
		? ((sqInt (*)(char *, sqInt))sCLPfn)(pathNameIndex, pathNameSize)
		: 1);
	status = (okToList
		? dir_Lookup(pathNameIndex, pathNameSize, index, entryName, (&entryNameSize), (&createDate), (&modifiedDate), (&dirFlag), (&fileSize), (&posixPermissions), (&symlinkFlag))
		: DirNoMoreEntries);
	if (failed(self)) {
		return null;
	}
	if (status == DirNoMoreEntries) {

		/* no more entries; return nil */
		/* pop pathName, index, rcvr */
		popthenPush(3, nilObject(self), self);
		return null;
	}
	if (status == DirBadPath) {
		return primitiveFail(self);
	}
	popthenPush(3, 
#  if PharoVM
		makeDirEntryNamesizecreateDatemodDateisDirfileSizeposixPermissionsisSymlink(entryName, entryNameSize, createDate, modifiedDate, dirFlag, fileSize, posixPermissions, symlinkFlag, self)
#  else /* PharoVM */
		makeDirEntryNamesizecreateDatemodDateisDirfileSize(entryName, entryNameSize, createDate, modifiedDate, dirFlag, fileSize, self)
#  endif /* PharoVM */
		, self);
	return 0;
}

	/* FilePlugin>>#primitiveDirectorySetMacTypeAndCreator */
EXPORT(sqInt)
primitiveDirectorySetMacTypeAndCreator(struct foo * self)
{
    sqInt creatorString;
    char *creatorStringIndex;
    sqInt fileName;
    char *fileNameIndex;
    sqInt fileNameSize;
    sqInt okToSet;
    sqInt typeString;
    char *typeStringIndex;

	creatorString = stackValue(0, self);
	typeString = stackValue(1, self);
	fileName = stackValue(2, self);
	if (!((isBytes(creatorString, self))
		 && ((isBytes(typeString, self))
		 && ((isBytes(fileName, self))
		 && (((byteSizeOf(creatorString, self)) == 4)
		 && ((byteSizeOf(typeString, self)) == 4)))))) {
		return primitiveFail(self);
	}
	creatorStringIndex = firstIndexableField(creatorString, self);
	typeStringIndex = firstIndexableField(typeString, self);
	fileNameIndex = firstIndexableField(fileName, self);

	/* If the security plugin can be loaded, use it to check for permission.
	   If not, assume it's ok */
	fileNameSize = byteSizeOf(fileName, self);
	if (sCSFTfn != 0) {
		okToSet = ((sqInt (*)(char *, sqInt))sCSFTfn)(fileNameIndex, fileNameSize);
		if (!okToSet) {
			return primitiveFail(self);
		}
	}
	if (!(dir_SetMacFileTypeAndCreator(fileNameIndex, fileNameSize, typeStringIndex, creatorStringIndex))) {
		return primitiveFail(self);
	}
	pop(3, self);
	return 0;
}


/*	If the security plugin can be loaded, use it to turn off file access
	If not, assume it's ok */

	/* FilePlugin>>#primitiveDisableFileAccess */
EXPORT(sqInt)
primitiveDisableFileAccess(struct foo * self)
{
	if (sDFAfn != 0) {
		((sqInt (*)(void))sDFAfn)();
	}
	return 0;
}

	/* FilePlugin>>#primitiveFileAtEnd */
EXPORT(sqInt)
primitiveFileAtEnd(struct foo * self)
{
    sqInt atEnd;
    SQFile *file;
    sqInt objectPointer;

	atEnd = 0;
	/* begin fileValueOf: */
	objectPointer = stackValue(0, self);
	if (!((isBytes(objectPointer, self))
		 && ((byteSizeOf(objectPointer, self)) == (sizeof(SQFile))))) {
		primitiveFail(self);
		file = null;
		goto l1;
	}
	file = firstIndexableField(objectPointer, self);
	l1:	/* end fileValueOf: */;
	if (!(failed(self))) {
		atEnd = sqFileAtEnd(file, self);
	}
	if (!(failed(self))) {
		methodReturnBool(atEnd, self);
	}
	return 0;
}

	/* FilePlugin>>#primitiveFileClose */
EXPORT(sqInt)
primitiveFileClose(struct foo * self)
{
    SQFile *file;
    sqInt objectPointer;

	/* begin fileValueOf: */
	objectPointer = stackValue(0, self);
	if (!((isBytes(objectPointer, self))
		 && ((byteSizeOf(objectPointer, self)) == (sizeof(SQFile))))) {
		primitiveFail(self);
		file = null;
		goto l1;
	}
	file = firstIndexableField(objectPointer, self);
	l1:	/* end fileValueOf: */;
	if (!(failed(self))) {
		sqFileClose(file, self);
	}
	if (!(failed(self))) {
		pop(1, self);
	}
	return 0;
}

	/* FilePlugin>>#primitiveFileDelete */
EXPORT(sqInt)
primitiveFileDelete(struct foo * self)
{
    char *nameIndex;
    sqInt namePointer;
    sqInt nameSize;
    sqInt okToDelete;

	namePointer = stackValue(0, self);
	if (!(isBytes(namePointer, self))) {
		return primitiveFail(self);
	}
	nameIndex = firstIndexableField(namePointer, self);

	/* If the security plugin can be loaded, use it to check for permission.
	   If not, assume it's ok */
	nameSize = byteSizeOf(namePointer, self);
	if (sCDFfn != 0) {
		okToDelete =  ((sqInt (*)(char *, sqInt))sCDFfn)(nameIndex, nameSize);
		if (!okToDelete) {
			return primitiveFail(self);
		}
	}
	sqFileDeleteNameSize(nameIndex, nameSize, self);
	if (!(failed(self))) {
		pop(1, self);
	}
	return 0;
}


/*	Allow to test if the standard input/output files are from a console or not
	Return values:
	* -1 - Error
	* 0 - no console (windows only)
	* 1 - normal terminal (unix terminal / windows console)
	* 2 - pipe
	* 3 - file
	* 4 - cygwin terminal (windows only) */

	/* FilePlugin>>#primitiveFileDescriptorType */
EXPORT(sqInt)
primitiveFileDescriptorType(struct foo * self)
{
    int fd;
    sqInt fdPointer;
    sqInt fileType;

	fdPointer = stackValue(0, self);
	if (!(isIntegerObject(fdPointer, self))) {
		return primitiveFailFor(PrimErrBadArgument, self);
	}
	fd = integerValueOf(fdPointer, self);
	if (failed(self)) {

		/* Ensure that the appropriate failure code has been set */
		return primitiveFailFor(PrimErrBadArgument, self);
	}
	fileType = sqFileDescriptorType(fd, self);
	methodReturnInteger(fileType, self);
	return 0;
}

	/* FilePlugin>>#primitiveFileFlush */
EXPORT(sqInt)
primitiveFileFlush(struct foo * self)
{
    SQFile *file;
    sqInt objectPointer;

	/* begin fileValueOf: */
	objectPointer = stackValue(0, self);
	if (!((isBytes(objectPointer, self))
		 && ((byteSizeOf(objectPointer, self)) == (sizeof(SQFile))))) {
		primitiveFail(self);
		file = null;
		goto l1;
	}
	file = firstIndexableField(objectPointer, self);
	l1:	/* end fileValueOf: */;
	if (!(failed(self))) {
		sqFileFlush(file, self);
	}
	if (!(failed(self))) {
		pop(1, self);
	}
	return 0;
}

	/* FilePlugin>>#primitiveFileGetPosition */
EXPORT(sqInt)
primitiveFileGetPosition(struct foo * self)
{
    SQFile *file;
    sqInt objectPointer;
    squeakFileOffsetType position;

	/* begin fileValueOf: */
	objectPointer = stackValue(0, self);
	if (!((isBytes(objectPointer, self))
		 && ((byteSizeOf(objectPointer, self)) == (sizeof(SQFile))))) {
		primitiveFail(self);
		file = null;
		goto l1;
	}
	file = firstIndexableField(objectPointer, self);
	l1:	/* end fileValueOf: */;
	if (!(failed(self))) {
		position = sqFileGetPosition(file, self);
	}
	if (!(failed(self))) {
		methodReturnValue(positive64BitIntegerFor(position, self), self);
	}
	return 0;
}

	/* FilePlugin>>#primitiveFileOpen */
EXPORT(sqInt)
primitiveFileOpen(struct foo * self)
{
    sqInt filePointer;
    char *nameIndex;
    sqInt namePointer;
    sqInt nameSize;
    sqInt writeFlag;

	writeFlag = booleanValueOf(stackValue(0, self), self);
	namePointer = stackValue(1, self);
	if (!(isBytes(namePointer, self))) {
		return primitiveFail(self);
	}
	nameIndex = firstIndexableField(namePointer, self);
	nameSize = byteSizeOf(namePointer, self);
	filePointer = fileOpenNamesizewritesecure(nameIndex, nameSize, writeFlag, 1, self);
	if (!(failed(self))) {
		methodReturnValue(filePointer, self);
	}
	return 0;
}

	/* FilePlugin>>#primitiveFileOpenNew */
EXPORT(sqInt)
primitiveFileOpenNew(struct foo * self)
{
    sqInt filePointer;
    char *nameIndex;
    sqInt namePointer;
    sqInt nameSize;

	namePointer = stackValue(0, self);
	if (!(isBytes(namePointer, self))) {
		return primitiveFail(self);
	}
	nameIndex = firstIndexableField(namePointer, self);
	nameSize = byteSizeOf(namePointer, self);
	filePointer = fileOpenNewNamesizesecure(nameIndex, nameSize, 1, self);
	if (!(failed(self))) {
		methodReturnValue(filePointer, self);
	}
	return 0;
}

	/* FilePlugin>>#primitiveFileRead */
EXPORT(sqInt)
primitiveFileRead(struct foo * self)
{
    sqInt array;
    sqInt array1;
    sqInt bytesRead;
    sqInt bytesRead1;
    size_t count;
    size_t count1;
    size_t elementSize;
    size_t elementSize1;
    SQFile *file;
    SQFile *file1;
    sqInt objectPointer;
    sqInt objectPointer1;
    sqInt retryCount;
    size_t slotSize;
    size_t startIndex;
    size_t startIndex1;

	
#  if SPURVM
	/* begin primitiveFileReadWithPinning */
	count = positiveMachineIntegerValueOf(stackValue(0, self), self);
	startIndex = positiveMachineIntegerValueOf(stackValue(1, self), self);
	array = stackValue(2, self);
	/* begin fileValueOf: */
	objectPointer = stackValue(3, self);
	if (!((isBytes(objectPointer, self))
		 && ((byteSizeOf(objectPointer, self)) == (sizeof(SQFile))))) {
		primitiveFail(self);
		file = null;
		goto l1;
	}
	file = firstIndexableField(objectPointer, self);
	l1:	/* end fileValueOf: */;
	if ((failed(self))
	 || (!(isWordsOrBytes(array, self)))) {
		primitiveFailFor(PrimErrBadArgument, self);
		goto l2;
	}
	slotSize = slotSizeOf(array, self);
	if (!((startIndex >= 1)
		 && (((startIndex + count) - 1) <= slotSize))) {
		primitiveFailFor(PrimErrBadIndex, self);
		goto l2;
	}
	elementSize = (slotSize == 0
		? 1
		: (byteSizeOf(array, self)) / slotSize);
	bytesRead = sqFileReadIntoAt(file, count * elementSize, ((char *) (firstIndexableField(array, self))), (startIndex - 1) * elementSize, self);
	if (!(failed(self))) {
		methodReturnValue(integerObjectOf(bytesRead / elementSize, self), self);
	}
	l2:	/* end primitiveFileReadWithPinning */;
#  else /* SPURVM */
	/* begin primitiveFileReadWithoutPinning */
	retryCount = 0;
	count1 = positive32BitValueOf(stackValue(0, self), self);
	startIndex1 = positive32BitValueOf(stackValue(1, self), self);
	while (1) {
		array1 = stackValue(2, self);
		/* begin fileValueOf: */
		objectPointer1 = stackValue(3, self);
		if (!((isBytes(objectPointer1, self))
			 && ((byteSizeOf(objectPointer1, self)) == (sizeof(SQFile))))) {
			primitiveFail(self);
			file1 = null;
			goto l3;
		}
		file1 = firstIndexableField(objectPointer1, self);
	l3:	/* end fileValueOf: */;
		if ((failed(self))
		 || (!(isWordsOrBytes(array1, self)))) {
			primitiveFailFor(PrimErrBadArgument, self);
			goto l4;
		}
		elementSize1 = (isWords(array1, self)
			? 4
			: 1);
		if (!((startIndex1 >= 1)
			 && (((startIndex1 + count1) - 1) <= (slotSizeOf(array1, self))))) {
			primitiveFailFor(PrimErrBadIndex, self);
			goto l4;
		}
		bytesRead1 = sqFileReadIntoAt(file1, count1 * elementSize1, ((char *) (firstIndexableField(array1, self))), (startIndex1 - 1) * elementSize1);
		if (!(((primitiveFailureCode(self)) == PrimErrObjectMayMove)
		 && (((retryCount += 1)) <= 2))) break;
		tenuringIncrementalGC(self);
		primitiveFailFor(PrimNoErr, self);
	}
	if (!(failed(self))) {
		methodReturnValue(integerObjectOf(bytesRead1 / elementSize1, self), self);
	}
	l4:	/* end primitiveFileReadWithoutPinning */;
#  endif /* SPURVM */
	return 0;
}


/*	This version of primitiveFileRead is for garbage collectors without
	support for pinning.
 */

	/* FilePlugin>>#primitiveFileReadWithoutPinning */
static sqInt
primitiveFileReadWithoutPinning(struct foo * self)
{
    sqInt array;
    sqInt bytesRead;
    size_t count;
    size_t elementSize;
    SQFile *file;
    sqInt objectPointer;
    sqInt retryCount;
    size_t startIndex;

	retryCount = 0;
	count = positive32BitValueOf(stackValue(0, self), self);
	startIndex = positive32BitValueOf(stackValue(1, self), self);
	while (1) {
		array = stackValue(2, self);
		/* begin fileValueOf: */
		objectPointer = stackValue(3, self);
		if (!((isBytes(objectPointer, self))
			 && ((byteSizeOf(objectPointer, self)) == (sizeof(SQFile))))) {
			primitiveFail(self);
			file = null;
			goto l1;
		}
		file = firstIndexableField(objectPointer, self);
	l1:	/* end fileValueOf: */;
		if ((failed(self))
		 || (!(isWordsOrBytes(array, self)))) {
			return primitiveFailFor(PrimErrBadArgument, self);
		}
		elementSize = (isWords(array, self)
			? 4
			: 1);
		if (!((startIndex >= 1)
			 && (((startIndex + count) - 1) <= (slotSizeOf(array, self))))) {
			return primitiveFailFor(PrimErrBadIndex, self);
		}
		bytesRead = sqFileReadIntoAt(file, count * elementSize, ((char *) (firstIndexableField(array, self))), (startIndex - 1) * elementSize, self);
		if (!(((primitiveFailureCode(self)) == PrimErrObjectMayMove)
		 && (((retryCount += 1)) <= 2))) break;
		tenuringIncrementalGC(self);
		primitiveFailFor(PrimNoErr, self);
	}
	if (!(failed(self))) {
		methodReturnValue(integerObjectOf(bytesRead / elementSize, self), self);
	}
	return 0;
}


/*	This version of primitiveFileRead is for garbage collectors that support
	pinning. 
 */

	/* FilePlugin>>#primitiveFileReadWithPinning */
static sqInt
primitiveFileReadWithPinning(struct foo * self)
{
    sqInt array;
    sqInt bytesRead;
    size_t count;
    size_t elementSize;
    SQFile *file;
    sqInt objectPointer;
    size_t slotSize;
    size_t startIndex;

	count = positiveMachineIntegerValueOf(stackValue(0, self), self);
	startIndex = positiveMachineIntegerValueOf(stackValue(1, self), self);
	array = stackValue(2, self);
	/* begin fileValueOf: */
	objectPointer = stackValue(3, self);
	if (!((isBytes(objectPointer, self))
		 && ((byteSizeOf(objectPointer, self)) == (sizeof(SQFile))))) {
		primitiveFail(self);
		file = null;
		goto l1;
	}
	file = firstIndexableField(objectPointer, self);
	l1:	/* end fileValueOf: */;
	if ((failed(self))
	 || (!(isWordsOrBytes(array, self)))) {
		return primitiveFailFor(PrimErrBadArgument, self);
	}
	slotSize = slotSizeOf(array, self);
	if (!((startIndex >= 1)
		 && (((startIndex + count) - 1) <= slotSize))) {
		return primitiveFailFor(PrimErrBadIndex, self);
	}
	elementSize = (slotSize == 0
		? 1
		: (byteSizeOf(array, self)) / slotSize);
	bytesRead = sqFileReadIntoAt(file, count * elementSize, ((char *) (firstIndexableField(array, self))), (startIndex - 1) * elementSize, self);
	if (!(failed(self))) {
		methodReturnValue(integerObjectOf(bytesRead / elementSize, self), self);
	}
	return 0;
}

	/* FilePlugin>>#primitiveFileRename */
EXPORT(sqInt)
primitiveFileRename(struct foo * self)
{
    char *newNameIndex;
    sqInt newNamePointer;
    sqInt newNameSize;
    sqInt okToRename;
    char *oldNameIndex;
    sqInt oldNamePointer;
    sqInt oldNameSize;

	newNamePointer = stackValue(0, self);
	oldNamePointer = stackValue(1, self);
	if (!((isBytes(newNamePointer, self))
		 && (isBytes(oldNamePointer, self)))) {
		return primitiveFail(self);
	}
	newNameIndex = firstIndexableField(newNamePointer, self);
	newNameSize = byteSizeOf(newNamePointer, self);
	oldNameIndex = firstIndexableField(oldNamePointer, self);

	/* If the security plugin can be loaded, use it to check for rename permission.
	   If not, assume it's ok */
	oldNameSize = byteSizeOf(oldNamePointer, self);
	if (sCRFfn != 0) {
		okToRename =  ((sqInt (*)(char *, sqInt))sCRFfn)(oldNameIndex, oldNameSize);
		if (!okToRename) {
			return primitiveFail(self);
		}
	}
	sqFileRenameOldSizeNewSize(oldNameIndex, oldNameSize, newNameIndex, newNameSize, self);
	if (!(failed(self))) {
		pop(2, self);
	}
	return 0;
}

	/* FilePlugin>>#primitiveFileSetPosition */
EXPORT(sqInt)
primitiveFileSetPosition(struct foo * self)
{
    SQFile *file;
    squeakFileOffsetType newPosition;
    sqInt objectPointer;

	if ((byteSizeOf(stackValue(0, self), self)) > (sizeof(squeakFileOffsetType))) {
		return primitiveFail(self);
	}
	newPosition = positive64BitValueOf(stackValue(0, self), self);
	/* begin fileValueOf: */
	objectPointer = stackValue(1, self);
	if (!((isBytes(objectPointer, self))
		 && ((byteSizeOf(objectPointer, self)) == (sizeof(SQFile))))) {
		primitiveFail(self);
		file = null;
		goto l1;
	}
	file = firstIndexableField(objectPointer, self);
	l1:	/* end fileValueOf: */;
	if (!(failed(self))) {
		sqFileSetPosition(file, newPosition, self);
	}
	if (!(failed(self))) {
		pop(2, self);
	}
	return 0;
}

	/* FilePlugin>>#primitiveFileSize */
EXPORT(sqInt)
primitiveFileSize(struct foo * self)
{
    SQFile *file;
    sqInt objectPointer;
    squeakFileOffsetType size;

	/* begin fileValueOf: */
	objectPointer = stackValue(0, self);
	if (!((isBytes(objectPointer, self))
		 && ((byteSizeOf(objectPointer, self)) == (sizeof(SQFile))))) {
		primitiveFail(self);
		file = null;
		goto l1;
	}
	file = firstIndexableField(objectPointer, self);
	l1:	/* end fileValueOf: */;
	if (!(failed(self))) {
		size = sqFileSize(file, self);
	}
	if (!(failed(self))) {
		methodReturnValue(positive64BitIntegerFor(size, self), self);
	}
	return 0;
}


/*	Answer an Array of file handles for standard in, standard out and standard
	error, with nil in entries that are unvailable, e.g. because the platform
	does not provide
	standard error, etc. Fail if an error occurs determining the stdio
	handles, if the security plugin denies access or if memory runs out. */

	/* FilePlugin>>#primitiveFileStdioHandles */
EXPORT(sqInt)
primitiveFileStdioHandles(struct foo * self)
{
    SQFile fileRecords[3];
    sqInt index;
    sqInt result;
    sqInt validMask;

	if (sHFAfn != 0) {
		if (!( ((sqInt (*)(void))sHFAfn)())) {
			return primitiveFailFor(PrimErrUnsupported, self);
		}
	}
	validMask = sqFileStdioHandlesInto(fileRecords);
	if (validMask < 0) {
		return primitiveFailForOSError(validMask, self);
	}
	result = instantiateClassindexableSize(classArray(self), 3, self);
	if (result == null) {
		return primitiveFailFor(PrimErrNoMemory, self);
	}
	pushRemappableOop(result, self);
	for (index = 0; index <= 2; index += 1) {
		if ((validMask & (1U << index)) != 0) {
			result = instantiateClassindexableSize(classByteArray(self), sizeof(SQFile), self);
			if (result == null) {
				popRemappableOop(self);
				return primitiveFailFor(PrimErrNoMemory, self);
			}
			storePointerofObjectwithValue(index, topRemappableOop(self), result, self);
			memcpy(firstIndexableField(result, self), (&(fileRecords[index])), sizeof(SQFile));
		}
	}
	
#  if COGMTVM
	
#  if SPURVM
#  else /* SPURVM */
	fullGC(self);
#  endif /* SPURVM */
#  endif /* COGMTVM */
	result = popRemappableOop(self);
	methodReturnValue(result, self);
	return 0;
}

	/* FilePlugin>>#primitiveFileSync */
EXPORT(sqInt)
primitiveFileSync(struct foo * self)
{
    SQFile *file;
    sqInt objectPointer;

	/* begin fileValueOf: */
	objectPointer = stackValue(0, self);
	if (!((isBytes(objectPointer, self))
		 && ((byteSizeOf(objectPointer, self)) == (sizeof(SQFile))))) {
		primitiveFail(self);
		file = null;
		goto l1;
	}
	file = firstIndexableField(objectPointer, self);
	l1:	/* end fileValueOf: */;
	if (!(failed(self))) {
		sqFileSync(file, self);
	}
	if (!(failed(self))) {
		pop(1, self);
	}
	return 0;
}


/*	ftruncate is not an ansi function so we have a macro to point to a
	suitable platform implementation
 */

	/* FilePlugin>>#primitiveFileTruncate */
EXPORT(sqInt)
primitiveFileTruncate(struct foo * self)
{
    SQFile *file;
    sqInt objectPointer;
    squeakFileOffsetType truncatePosition;

	if (!(isIntegerObject(stackValue(0, self), self))) {
		if ((byteSizeOf(stackValue(0, self), self)) > (sizeof(squeakFileOffsetType))) {
			return primitiveFail(self);
		}
	}
	truncatePosition = positive64BitValueOf(stackValue(0, self), self);
	/* begin fileValueOf: */
	objectPointer = stackValue(1, self);
	if (!((isBytes(objectPointer, self))
		 && ((byteSizeOf(objectPointer, self)) == (sizeof(SQFile))))) {
		primitiveFail(self);
		file = null;
		goto l1;
	}
	file = firstIndexableField(objectPointer, self);
	l1:	/* end fileValueOf: */;
	if (!(failed(self))) {
		sqFileTruncate(file, truncatePosition, self);
	}
	if (!(failed(self))) {
		pop(2, self);
	}
	return 0;
}

	/* FilePlugin>>#primitiveFileWrite */
EXPORT(sqInt)
primitiveFileWrite(struct foo * self)
{
    sqInt array;
    sqInt bytesWritten;
    size_t count;
    size_t elementSize;
    SQFile *file;
    sqInt objectPointer;
    size_t slotSize;
    size_t startIndex;

	count = positiveMachineIntegerValueOf(stackValue(0, self), self);
	startIndex = positiveMachineIntegerValueOf(stackValue(1, self), self);
	array = stackValue(2, self);
	/* begin fileValueOf: */
	objectPointer = stackValue(3, self);
	if (!((isBytes(objectPointer, self))
		 && ((byteSizeOf(objectPointer, self)) == (sizeof(SQFile))))) {
		primitiveFail(self);
		file = null;
		goto l1;
	}
	file = firstIndexableField(objectPointer, self);
	l1:	/* end fileValueOf: */;
	if ((failed(self))
	 || (!(isWordsOrBytes(array, self)))) {
		return primitiveFailFor(PrimErrBadArgument, self);
	}
	slotSize = slotSizeOf(array, self);
	if (!((startIndex >= 1)
		 && (((startIndex + count) - 1) <= slotSize))) {
		return primitiveFailFor(PrimErrBadIndex, self);
	}
	elementSize = (slotSize == 0
		? 1
		: (byteSizeOf(array, self)) / slotSize);
	bytesWritten = sqFileWriteFromAt(file, count * elementSize, ((char *) (firstIndexableField(array, self))), (startIndex - 1) * elementSize, self);
	if (!(failed(self))) {
		methodReturnValue(integerObjectOf(bytesWritten / elementSize, self), self);
	}
	return 0;
}

	/* FilePlugin>>#primitiveHasFileAccess */
EXPORT(sqInt)
primitiveHasFileAccess(struct foo * self)
{
    sqInt hasAccess;


	/* If the security plugin can be loaded, use it to check .
	   If not, assume it's ok */
	if (sHFAfn != 0) {
		hasAccess =  ((sqInt (*)(void))sHFAfn)();
	}
	else {
		hasAccess = 1;
	}
	methodReturnBool(hasAccess, self);
	return 0;
}


/*	Note: This is coded so that it can be run in Squeak. */

	/* InterpreterPlugin>>#setInterpreter: */
EXPORT(sqInt)
setInterpreter(struct VirtualMachine *anInterpreter)
{
    sqInt ok;

	interpreterProxy = anInterpreter;
	ok = ((interpreterProxy->majorVersion()) == (VM_PROXY_MAJOR))
	 && ((interpreterProxy->minorVersion()) >= (VM_PROXY_MINOR));
	if (ok) {
		
#if !defined(SQUEAK_BUILTIN_PLUGIN)
		arrayValueOf = interpreterProxy->arrayValueOf;
		booleanValueOf = interpreterProxy->booleanValueOf;
		byteSizeOf = interpreterProxy->byteSizeOf;
#if VM_PROXY_MAJOR > 1 || (VM_PROXY_MAJOR == 1 && VM_PROXY_MINOR >= 13)
		characterObjectOf = interpreterProxy->characterObjectOf;
#else
#if !defined(characterObjectOf)
		characterObjectOf = 0;
#endif
#endif
		characterTable = interpreterProxy->characterTable;
		classArray = interpreterProxy->classArray;
		classByteArray = interpreterProxy->classByteArray;
		classString = interpreterProxy->classString;
		failed = interpreterProxy->failed;
		falseObject = interpreterProxy->falseObject;
		fetchPointerofObject = interpreterProxy->fetchPointerofObject;
		firstIndexableField = interpreterProxy->firstIndexableField;
		fullGC = interpreterProxy->fullGC;
		instantiateClassindexableSize = interpreterProxy->instantiateClassindexableSize;
		integerObjectOf = interpreterProxy->integerObjectOf;
		integerValueOf = interpreterProxy->integerValueOf;
		ioLoadFunctionFrom = interpreterProxy->ioLoadFunctionFrom;
		isKindOf = interpreterProxy->isKindOf;
		isBytes = interpreterProxy->isBytes;
		isIntegerObject = interpreterProxy->isIntegerObject;
		isWords = interpreterProxy->isWords;
		isWordsOrBytes = interpreterProxy->isWordsOrBytes;
		methodReturnBool = interpreterProxy->methodReturnBool;
		methodReturnInteger = interpreterProxy->methodReturnInteger;
		methodReturnValue = interpreterProxy->methodReturnValue;
		nilObject = interpreterProxy->nilObject;
		pop = interpreterProxy->pop;
		popthenPush = interpreterProxy->popthenPush;
		popRemappableOop = interpreterProxy->popRemappableOop;
		positive32BitIntegerFor = interpreterProxy->positive32BitIntegerFor;
		positive32BitValueOf = interpreterProxy->positive32BitValueOf;
		positive64BitIntegerFor = interpreterProxy->positive64BitIntegerFor;
		positive64BitValueOf = interpreterProxy->positive64BitValueOf;
		positiveMachineIntegerValueOf = interpreterProxy->positiveMachineIntegerValueOf;
		primitiveFail = interpreterProxy->primitiveFail;
		primitiveFailFor = interpreterProxy->primitiveFailFor;
#if VM_PROXY_MAJOR > 1 || (VM_PROXY_MAJOR == 1 && VM_PROXY_MINOR >= 14)
		primitiveFailForOSError = interpreterProxy->primitiveFailForOSError;
#else
#if !defined(primitiveFailForOSError)
		primitiveFailForOSError = 0;
#endif
#endif
		primitiveFailureCode = interpreterProxy->primitiveFailureCode;
		pushRemappableOop = interpreterProxy->pushRemappableOop;
		slotSizeOf = interpreterProxy->slotSizeOf;
		stSizeOf = interpreterProxy->stSizeOf;
		stackIntegerValue = interpreterProxy->stackIntegerValue;
		stackValue = interpreterProxy->stackValue;
		storePointerofObjectwithValue = interpreterProxy->storePointerofObjectwithValue;
		tenuringIncrementalGC = interpreterProxy->tenuringIncrementalGC;
		topRemappableOop = interpreterProxy->topRemappableOop;
		trueObject = interpreterProxy->trueObject;
#endif /* !defined(SQUEAK_BUILTIN_PLUGIN) */
	}
	return ok;
}


/*	Exported entry point for the VM. Needed for image saving only and no-op on
	anything but Macs.
 */

	/* FilePlugin>>#setMacFile:Type:AndCreator: */
EXPORT(sqInt)
setMacFileTypeAndCreator(char *fileName, char *typeString, char *creatorString, struct foo * self)
{
	return dir_SetMacFileTypeAndCreator(fileName, strlen(fileName), typeString, creatorString);
}

	/* FilePlugin>>#shutdownModule */
EXPORT(sqInt)
shutdownModule(struct foo * self)
{
	return sqFileShutdown(self);
}


#ifdef SQUEAK_BUILTIN_PLUGIN

static char _m[] = "FilePlugin";
void* FilePlugin_exports[][3] = {
	{(void*)_m, "fileOpenNamesizewritesecure", (void*)fileOpenNamesizewritesecure},
	{(void*)_m, "fileOpenNewNamesizesecure", (void*)fileOpenNewNamesizesecure},
	{(void*)_m, "getModuleName", (void*)getModuleName},
	{(void*)_m, "initialiseModule", (void*)initialiseModule},
	{(void*)_m, "moduleUnloaded", (void*)moduleUnloaded},
	{(void*)_m, "primitiveConnectToFile\000\001", (void*)primitiveConnectToFile},
	{(void*)_m, "primitiveConnectToFileDescriptor\000\000", (void*)primitiveConnectToFileDescriptor},
	{(void*)_m, "primitiveDirectoryCreate\000\001", (void*)primitiveDirectoryCreate},
	{(void*)_m, "primitiveDirectoryDelete\000\001", (void*)primitiveDirectoryDelete},
	{(void*)_m, "primitiveDirectoryDelimitor\000\377", (void*)primitiveDirectoryDelimitor},
	{(void*)_m, "primitiveDirectoryEntry\000\001", (void*)primitiveDirectoryEntry},
	{(void*)_m, "primitiveDirectoryGetMacTypeAndCreator\000\001", (void*)primitiveDirectoryGetMacTypeAndCreator},
	{(void*)_m, "primitiveDirectoryLookup\000\001", (void*)primitiveDirectoryLookup},
	{(void*)_m, "primitiveDirectorySetMacTypeAndCreator\000\001", (void*)primitiveDirectorySetMacTypeAndCreator},
	{(void*)_m, "primitiveDisableFileAccess\000\377", (void*)primitiveDisableFileAccess},
	{(void*)_m, "primitiveFileAtEnd\000\001", (void*)primitiveFileAtEnd},
	{(void*)_m, "primitiveFileClose\000\001", (void*)primitiveFileClose},
	{(void*)_m, "primitiveFileDelete\000\001", (void*)primitiveFileDelete},
	{(void*)_m, "primitiveFileDescriptorType\000\000", (void*)primitiveFileDescriptorType},
	{(void*)_m, "primitiveFileFlush\000\001", (void*)primitiveFileFlush},
	{(void*)_m, "primitiveFileGetPosition\000\001", (void*)primitiveFileGetPosition},
	{(void*)_m, "primitiveFileOpen\000\002", (void*)primitiveFileOpen},
	{(void*)_m, "primitiveFileOpenNew\000\002", (void*)primitiveFileOpenNew},
	{(void*)_m, "primitiveFileRead\000\001", (void*)primitiveFileRead},
	{(void*)_m, "primitiveFileRename\000\001", (void*)primitiveFileRename},
	{(void*)_m, "primitiveFileSetPosition\000\001", (void*)primitiveFileSetPosition},
	{(void*)_m, "primitiveFileSize\000\001", (void*)primitiveFileSize},
	{(void*)_m, "primitiveFileStdioHandles\000\377", (void*)primitiveFileStdioHandles},
	{(void*)_m, "primitiveFileSync\000\001", (void*)primitiveFileSync},
	{(void*)_m, "primitiveFileTruncate\000\001", (void*)primitiveFileTruncate},
	{(void*)_m, "primitiveFileWrite\000\001", (void*)primitiveFileWrite},
	{(void*)_m, "primitiveHasFileAccess\000\377", (void*)primitiveHasFileAccess},
	{(void*)_m, "setInterpreter", (void*)setInterpreter},
	{(void*)_m, "setMacFileTypeAndCreator", (void*)setMacFileTypeAndCreator},
	{(void*)_m, "shutdownModule\000\377", (void*)shutdownModule},
	{NULL, NULL, NULL}
};

#else /* ifdef SQ_BUILTIN_PLUGIN */

EXPORT(signed char) primitiveConnectToFileAccessorDepth = 1;
EXPORT(signed char) primitiveConnectToFileDescriptorAccessorDepth = 0;
EXPORT(signed char) primitiveDirectoryCreateAccessorDepth = 1;
EXPORT(signed char) primitiveDirectoryDeleteAccessorDepth = 1;
EXPORT(signed char) primitiveDirectoryEntryAccessorDepth = 1;
EXPORT(signed char) primitiveDirectoryGetMacTypeAndCreatorAccessorDepth = 1;
EXPORT(signed char) primitiveDirectoryLookupAccessorDepth = 1;
EXPORT(signed char) primitiveDirectorySetMacTypeAndCreatorAccessorDepth = 1;
EXPORT(signed char) primitiveFileAtEndAccessorDepth = 1;
EXPORT(signed char) primitiveFileCloseAccessorDepth = 1;
EXPORT(signed char) primitiveFileDeleteAccessorDepth = 1;
EXPORT(signed char) primitiveFileDescriptorTypeAccessorDepth = 0;
EXPORT(signed char) primitiveFileFlushAccessorDepth = 1;
EXPORT(signed char) primitiveFileGetPositionAccessorDepth = 1;
EXPORT(signed char) primitiveFileOpenAccessorDepth = 2;
EXPORT(signed char) primitiveFileOpenNewAccessorDepth = 2;
EXPORT(signed char) primitiveFileReadAccessorDepth = 1;
EXPORT(signed char) primitiveFileRenameAccessorDepth = 1;
EXPORT(signed char) primitiveFileSetPositionAccessorDepth = 1;
EXPORT(signed char) primitiveFileSizeAccessorDepth = 1;
EXPORT(signed char) primitiveFileSyncAccessorDepth = 1;
EXPORT(signed char) primitiveFileTruncateAccessorDepth = 1;
EXPORT(signed char) primitiveFileWriteAccessorDepth = 1;

#endif /* ifdef SQ_BUILTIN_PLUGIN */
