/* Automatically generated by
	SmartSyntaxPluginCodeGenerator VMMaker.oscog-eem.2493 uuid: d7437cc5-75c7-4a43-af6b-0f85bf0cebe6
   from
	JPEGReadWriter2Plugin VMMaker.oscog-eem.2493 uuid: d7437cc5-75c7-4a43-af6b-0f85bf0cebe6
 */
static char __buildInfo[] = "JPEGReadWriter2Plugin VMMaker.oscog-eem.2493 uuid: d7437cc5-75c7-4a43-af6b-0f85bf0cebe6 " __DATE__ ;



#include "config.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* Default EXPORT macro that does nothing (see comment in sq.h): */
#define EXPORT(returnType) returnType

/* Do not include the entire sq.h file but just those parts needed. */
#include "sqConfig.h"			/* Configuration options */
#include "sqVirtualMachine.h"	/*  The virtual machine proxy definition */
#include "sqPlatformSpecific.h"	/* Platform specific definitions */

#define true 1
#define false 0
#define null 0  /* using 'null' because nil is predefined in Think C */
#ifdef SQUEAK_BUILTIN_PLUGIN
# undef EXPORT
# define EXPORT(returnType) static returnType
#endif

#include "JPEGReadWriter2Plugin.h"
#include "sqMemoryAccess.h"


/*** Constants ***/
#define PrimErrBadArgument 3


/*** Function Prototypes ***/
EXPORT(const char*) getModuleName(void);
EXPORT(sqInt) primImageHeight(struct foo * self);
EXPORT(sqInt) primImageNumComponents(struct foo * self);
EXPORT(sqInt) primImageWidth(struct foo * self);
EXPORT(sqInt) primJPEGCompressStructSize(struct foo * self);
EXPORT(sqInt) primJPEGDecompressStructSize(struct foo * self);
EXPORT(sqInt) primJPEGErrorMgr2StructSize(struct foo * self);
EXPORT(sqInt) primJPEGPluginIsPresent(struct foo * self);
EXPORT(sqInt) primJPEGReadHeaderfromByteArrayerrorMgr(struct foo * self);
EXPORT(sqInt) primJPEGReadImagefromByteArrayonFormdoDitheringerrorMgr(struct foo * self);
EXPORT(sqInt) primJPEGWriteImageonByteArrayformqualityprogressiveJPEGerrorMgr(struct foo * self);
EXPORT(sqInt) primSupports8BitGrayscaleJPEGs(struct foo * self);
EXPORT(sqInt) setInterpreter(struct VirtualMachine *anInterpreter);
static sqInt sqAssert(sqInt aBool, struct foo * self);


/*** Variables ***/

#if !defined(SQUEAK_BUILTIN_PLUGIN)
static sqInt (*booleanValueOf)(sqInt obj, struct foo * self);
static sqInt (*byteSizeOf)(sqInt oop, struct foo * self);
static sqInt (*failed)(struct foo * self);
static sqInt (*falseObject)(struct foo * self);
static sqInt (*fetchIntegerofObject)(sqInt fieldIndex, sqInt objectPointer, struct foo * self);
static sqInt (*fetchPointerofObject)(sqInt index, sqInt oop, struct foo * self);
static void * (*firstIndexableField)(sqInt oop, struct foo * self);
static sqInt (*integerObjectOf)(sqInt value, struct foo * self);
static sqInt (*isKindOf)(sqInt oop, char *aString, struct foo * self);
static sqInt (*isBooleanObject)(sqInt oop, struct foo * self);
static sqInt (*isBytes)(sqInt oop, struct foo * self);
static sqInt (*isIntegerObject)(sqInt objectPointer, struct foo * self);
static sqInt (*isWordsOrBytes)(sqInt oop, struct foo * self);
static sqInt (*pop)(sqInt nItems, struct foo * self);
static sqInt (*popthenPush)(sqInt nItems, sqInt oop, struct foo * self);
static sqInt (*primitiveFail)(struct foo * self);
static sqInt (*primitiveFailFor)(sqInt reasonCode, struct foo * self);
static sqInt (*stSizeOf)(sqInt oop, struct foo * self);
static sqInt (*stackIntegerValue)(sqInt offset, struct foo * self);
static sqInt (*stackValue)(sqInt offset, struct foo * self);
static sqInt (*success)(sqInt aBoolean, struct foo * self);
static sqInt (*trueObject)(struct foo * self);
#else /* !defined(SQUEAK_BUILTIN_PLUGIN) */
extern sqInt booleanValueOf(sqInt obj, struct foo * self);
extern sqInt byteSizeOf(sqInt oop, struct foo * self);
extern sqInt failed(struct foo * self);
extern sqInt falseObject(struct foo * self);
extern sqInt fetchIntegerofObject(sqInt fieldIndex, sqInt objectPointer, struct foo * self);
extern sqInt fetchPointerofObject(sqInt index, sqInt oop, struct foo * self);
extern void * firstIndexableField(sqInt oop, struct foo * self);
extern sqInt integerObjectOf(sqInt value, struct foo * self);
extern sqInt isKindOf(sqInt oop, char *aString, struct foo * self);
#if VM_PROXY_MAJOR > 1 || (VM_PROXY_MAJOR == 1 && VM_PROXY_MINOR >= 15)
extern sqInt isBooleanObject(sqInt oop, struct foo * self);
#else
# define isBooleanObject(oop) 0
#endif
extern sqInt isBytes(sqInt oop, struct foo * self);
#if !defined(isIntegerObject)
extern sqInt isIntegerObject(sqInt objectPointer, struct foo * self);
#endif
extern sqInt isWordsOrBytes(sqInt oop, struct foo * self);
extern sqInt pop(sqInt nItems, struct foo * self);
extern sqInt popthenPush(sqInt nItems, sqInt oop, struct foo * self);
extern sqInt primitiveFail(struct foo * self);
extern sqInt primitiveFailFor(sqInt reasonCode, struct foo * self);
extern sqInt stSizeOf(sqInt oop, struct foo * self);
extern sqInt stackIntegerValue(sqInt offset, struct foo * self);
extern sqInt stackValue(sqInt offset, struct foo * self);
extern sqInt success(sqInt aBoolean, struct foo * self);
extern sqInt trueObject(struct foo * self);
extern
#endif
struct VirtualMachine* interpreterProxy;
static const char *moduleName =
#ifdef SQUEAK_BUILTIN_PLUGIN
	"JPEGReadWriter2Plugin VMMaker.oscog-eem.2493 (i)"
#else
	"JPEGReadWriter2Plugin VMMaker.oscog-eem.2493 (e)"
#endif
;



/*	Note: This is hardcoded so it can be run from Squeak.
	The module name is used for validating a module *after*
	it is loaded to check if it does really contain the module
	we're thinking it contains. This is important! */

	/* InterpreterPlugin>>#getModuleName */
EXPORT(const char*)
getModuleName(void)
{
	return moduleName;
}

	/* JPEGReadWriter2Plugin>>#primImageHeight: */
EXPORT(sqInt)
primImageHeight(struct foo * self)
{
	char *aJPEGDecompressStruct;
	sqInt _return_value;

	if (!(isBytes(stackValue(0, self), self))) {
		primitiveFailFor(PrimErrBadArgument, self);
		return null;
	}
	aJPEGDecompressStruct = ((char *) (firstIndexableField(stackValue(0, self), self)));
	if (failed(self)) {
		return null;
	}
	if (!((byteSizeOf(((sqInt)(sqIntptr_t)(aJPEGDecompressStruct) - BaseHeaderSize), self)) >= (sizeof(struct jpeg_decompress_struct)))) {
		primitiveFail(self);
		return null;
	}
	if (!(failed(self))) {
		_return_value = integerObjectOf((((j_decompress_ptr)aJPEGDecompressStruct)->image_height), self);
		if (!(failed(self))) {
			popthenPush(2, _return_value, self);
		}
	}
	return null;
}

	/* JPEGReadWriter2Plugin>>#primImageNumComponents: */
EXPORT(sqInt)
primImageNumComponents(struct foo * self)
{
	char *aJPEGDecompressStruct;
	sqInt _return_value;

	if (!(isBytes(stackValue(0, self), self))) {
		primitiveFailFor(PrimErrBadArgument, self);
		return null;
	}
	aJPEGDecompressStruct = ((char *) (firstIndexableField(stackValue(0, self), self)));
	if (failed(self)) {
		return null;
	}
	if (!((byteSizeOf(((sqInt)(sqIntptr_t)(aJPEGDecompressStruct) - BaseHeaderSize), self)) >= (sizeof(struct jpeg_decompress_struct)))) {
		primitiveFail(self);
		return null;
	}
	if (!(failed(self))) {
		_return_value = integerObjectOf((((j_decompress_ptr)aJPEGDecompressStruct)->num_components), self);
		if (!(failed(self))) {
			popthenPush(2, _return_value, self);
		}
	}
	return null;
}

	/* JPEGReadWriter2Plugin>>#primImageWidth: */
EXPORT(sqInt)
primImageWidth(struct foo * self)
{
	char *aJPEGDecompressStruct;
	sqInt _return_value;

	if (!(isBytes(stackValue(0, self), self))) {
		primitiveFailFor(PrimErrBadArgument, self);
		return null;
	}
	aJPEGDecompressStruct = ((char *) (firstIndexableField(stackValue(0, self), self)));
	if (failed(self)) {
		return null;
	}
	if (!((byteSizeOf(((sqInt)(sqIntptr_t)(aJPEGDecompressStruct) - BaseHeaderSize), self)) >= (sizeof(struct jpeg_decompress_struct)))) {
		primitiveFail(self);
		return null;
	}
	if (!(failed(self))) {
		_return_value = integerObjectOf((((j_decompress_ptr)aJPEGDecompressStruct)->image_width), self);
		if (!(failed(self))) {
			popthenPush(2, _return_value, self);
		}
	}
	return null;
}

	/* JPEGReadWriter2Plugin>>#primJPEGCompressStructSize */
EXPORT(sqInt)
primJPEGCompressStructSize(struct foo * self)
{
	sqInt _return_value;

	_return_value = integerObjectOf((sizeof(struct jpeg_compress_struct)), self);
	if (!(failed(self))) {
		popthenPush(1, _return_value, self);
	}
	return null;
}

	/* JPEGReadWriter2Plugin>>#primJPEGDecompressStructSize */
EXPORT(sqInt)
primJPEGDecompressStructSize(struct foo * self)
{
	sqInt _return_value;

	_return_value = integerObjectOf((sizeof(struct jpeg_decompress_struct)), self);
	if (!(failed(self))) {
		popthenPush(1, _return_value, self);
	}
	return null;
}

	/* JPEGReadWriter2Plugin>>#primJPEGErrorMgr2StructSize */
EXPORT(sqInt)
primJPEGErrorMgr2StructSize(struct foo * self)
{
	sqInt _return_value;

	_return_value = integerObjectOf((sizeof(struct error_mgr2)), self);
	if (!(failed(self))) {
		popthenPush(1, _return_value, self);
	}
	return null;
}

	/* JPEGReadWriter2Plugin>>#primJPEGPluginIsPresent */
EXPORT(sqInt)
primJPEGPluginIsPresent(struct foo * self)
{
	sqInt _return_value;

	_return_value = ((1) ? trueObject(self) : falseObject(self));
	if (!(failed(self))) {
		popthenPush(1, _return_value, self);
	}
	return null;
}

	/* JPEGReadWriter2Plugin>>#primJPEGReadHeader:fromByteArray:errorMgr: */
EXPORT(sqInt)
primJPEGReadHeaderfromByteArrayerrorMgr(struct foo * self)
{
	char *aJPEGDecompressStruct;
	char *aJPEGErrorMgr2Struct;
	char *source;
	sqInt sourceSize;

	if (!((isBytes(stackValue(2, self), self))
		 && ((isBytes(stackValue(1, self), self))
		 && (isBytes(stackValue(0, self), self))))) {
		primitiveFailFor(PrimErrBadArgument, self);
		return null;
	}
	aJPEGDecompressStruct = ((char *) (firstIndexableField(stackValue(2, self), self)));
	source = ((char *) (firstIndexableField(stackValue(1, self), self)));
	aJPEGErrorMgr2Struct = ((char *) (firstIndexableField(stackValue(0, self), self)));
	if (failed(self)) {
		return null;
	}
	if (!(((byteSizeOf(((sqInt)(sqIntptr_t)(aJPEGDecompressStruct) - BaseHeaderSize), self)) >= (sizeof(struct jpeg_decompress_struct)))
		 && ((byteSizeOf(((sqInt)(sqIntptr_t)(aJPEGErrorMgr2Struct) - BaseHeaderSize), self)) >= (sizeof(struct error_mgr2))))) {
		primitiveFail(self);
		return null;
	}
	sourceSize = byteSizeOf(((sqInt)(sqIntptr_t)(source) - BaseHeaderSize), self);
	if (sourceSize > 0) {
		primJPEGReadHeaderfromByteArraysizeerrorMgrReadHeader(aJPEGDecompressStruct, source, sourceSize, aJPEGErrorMgr2Struct);
	}
	if (!(failed(self))) {
		pop(3, self);
	}
	return null;
}

	/* JPEGReadWriter2Plugin>>#primJPEGReadImage:fromByteArray:onForm:doDithering:errorMgr: */
EXPORT(sqInt)
primJPEGReadImagefromByteArrayonFormdoDitheringerrorMgr(struct foo * self)
{
	char *aJPEGDecompressStruct;
	char *aJPEGErrorMgr2Struct;
	sqInt ditherFlag;
	sqInt form;
	unsigned int *formBitmap;
	sqInt formBitmapOOP;
	sqInt formBitmapSizeInBytes;
	int formComponentBitSize;
	int formComponents;
	sqInt formDepth;
	sqInt formHeight;
	sqInt formNativeDepth;
	sqInt formPitch;
	sqInt formWidth;
	int pixelsPerWord;
	char *source;
	sqInt sourceSize;
	sqInt wordsPerRow;

	if (!((isBytes(stackValue(4, self), self))
		 && ((isBytes(stackValue(3, self), self))
		 && ((isKindOf(stackValue(2, self), "Form", self))
		 && ((isBooleanObject(stackValue(1, self), self))
		 && (isBytes(stackValue(0, self), self))))))) {
		primitiveFailFor(PrimErrBadArgument, self);
		return null;
	}
	aJPEGDecompressStruct = ((char *) (firstIndexableField(stackValue(4, self), self)));
	source = ((char *) (firstIndexableField(stackValue(3, self), self)));
	form = stackValue(2, self);
	ditherFlag = booleanValueOf(stackValue(1, self), self);
	aJPEGErrorMgr2Struct = ((char *) (firstIndexableField(stackValue(0, self), self)));
	if (failed(self)) {
		return null;
	}
	formBitmapOOP = fetchPointerofObject(0, form, self);
	formNativeDepth = fetchIntegerofObject(3, form, self);
	formWidth = fetchIntegerofObject(1, form, self);
	formHeight = fetchIntegerofObject(2, form, self);

	/* Various parameter checks */
	formDepth = SQABS(formNativeDepth);
	if (!(((byteSizeOf(((sqInt)(sqIntptr_t)(aJPEGDecompressStruct) - BaseHeaderSize), self)) >= (sizeof(struct jpeg_decompress_struct)))
		 && ((byteSizeOf(((sqInt)(sqIntptr_t)(aJPEGErrorMgr2Struct) - BaseHeaderSize), self)) >= (sizeof(struct error_mgr2))))) {
		primitiveFail(self);
		return null;
	}
	formComponents = (formDepth != 8
		? 4
		: 1);
	formComponentBitSize = (formDepth != 16
		? 8
		: 4);
	pixelsPerWord = 32 / (formComponents * formComponentBitSize);
	wordsPerRow = ((formWidth + pixelsPerWord) - 1) / pixelsPerWord;
	formPitch = ((formWidth + (pixelsPerWord - 1)) / pixelsPerWord) * 4;
	formBitmapSizeInBytes = byteSizeOf(formBitmapOOP, self);
	success((isWordsOrBytes(formBitmapOOP, self))
	 && (formBitmapSizeInBytes >= (formPitch * formHeight)), self);
	if (failed(self)) {
		return null;
	}
	sourceSize = stSizeOf(stackValue(3, self), self);
	success(sourceSize != 0, self);
	if (failed(self)) {
		return null;
	}
	formBitmap = firstIndexableField(formBitmapOOP, self);
	primJPEGReadImagefromByteArrayonFormdoDitheringerrorMgrReadScanlines(aJPEGDecompressStruct, aJPEGErrorMgr2Struct, source, sourceSize, ditherFlag, formBitmap, pixelsPerWord, wordsPerRow, formNativeDepth);
	if (!(failed(self))) {
		pop(5, self);
	}
	return null;
}

	/* JPEGReadWriter2Plugin>>#primJPEGWriteImage:onByteArray:form:quality:progressiveJPEG:errorMgr: */
EXPORT(sqInt)
primJPEGWriteImageonByteArrayformqualityprogressiveJPEGerrorMgr(struct foo * self)
{
	char *aJPEGCompressStruct;
	char *aJPEGErrorMgr2Struct;
	char *destination;
	unsigned int destinationSize;
	sqInt form;
	unsigned int *formBitmap;
	sqInt formBitmapOOP;
	sqInt formBitmapSizeInBytes;
	int formComponentBitSize;
	int formComponents;
	sqInt formDepth;
	sqInt formHeight;
	sqInt formNativeDepth;
	sqInt formPitch;
	sqInt formWidth;
	int pixelsPerWord;
	sqInt progressiveFlag;
	sqInt quality;
	sqInt v;
	sqInt wordsPerRow;
	sqInt _return_value;

	v = 0;
	if (!((isBytes(stackValue(5, self), self))
		 && ((isBytes(stackValue(4, self), self))
		 && ((isKindOf(stackValue(3, self), "Form", self))
		 && ((isIntegerObject(stackValue(2, self), self))
		 && ((isBooleanObject(stackValue(1, self), self))
		 && (isBytes(stackValue(0, self), self)))))))) {
		primitiveFailFor(PrimErrBadArgument, self);
		return null;
	}
	aJPEGCompressStruct = ((char *) (firstIndexableField(stackValue(5, self), self)));
	destination = ((char *) (firstIndexableField(stackValue(4, self), self)));
	form = stackValue(3, self);
	quality = stackIntegerValue(2, self);
	progressiveFlag = booleanValueOf(stackValue(1, self), self);
	aJPEGErrorMgr2Struct = ((char *) (firstIndexableField(stackValue(0, self), self)));
	if (failed(self)) {
		return null;
	}
	formBitmapOOP = fetchPointerofObject(0, form, self);
	formWidth = fetchIntegerofObject(1, form, self);
	formHeight = fetchIntegerofObject(2, form, self);
	formNativeDepth = fetchIntegerofObject(3, form, self);

	/* Various parameter checks */
	formDepth = SQABS(formNativeDepth);
	if (!(((byteSizeOf(((sqInt)(sqIntptr_t)(aJPEGCompressStruct) - BaseHeaderSize), self)) >= (sizeof(struct jpeg_compress_struct)))
		 && ((byteSizeOf(((sqInt)(sqIntptr_t)(aJPEGErrorMgr2Struct) - BaseHeaderSize), self)) >= (sizeof(struct error_mgr2))))) {
		primitiveFail(self);
		return null;
	}
	formComponents = (formDepth != 8
		? 4
		: 1);
	formComponentBitSize = (formDepth != 16
		? 8
		: 4);
	pixelsPerWord = 32 / (formComponents * formComponentBitSize);
	wordsPerRow = ((formWidth + pixelsPerWord) - 1) / pixelsPerWord;
	formPitch = wordsPerRow * 4;
	formBitmapSizeInBytes = byteSizeOf(formBitmapOOP, self);
	success((isWordsOrBytes(formBitmapOOP, self))
	 && (formBitmapSizeInBytes >= (formPitch * formHeight)), self);
	if (failed(self)) {
		return null;
	}
	formBitmap = firstIndexableField(formBitmapOOP, self);
	destinationSize = stSizeOf(stackValue(4, self), self);
	if (destinationSize > 0) {
		primJPEGWriteImageonByteArrayformqualityprogressiveJPEGerrorMgrWriteScanlines(formWidth, formHeight, formNativeDepth, formBitmap, aJPEGCompressStruct, aJPEGErrorMgr2Struct, quality, progressiveFlag, pixelsPerWord, wordsPerRow, destination, (&destinationSize));
	}
	if (!(failed(self))) {
		_return_value = integerObjectOf(destinationSize, self);
		if (!(failed(self))) {
			popthenPush(7, _return_value, self);
		}
	}
	return null;
}

	/* JPEGReadWriter2Plugin>>#primSupports8BitGrayscaleJPEGs */
EXPORT(sqInt)
primSupports8BitGrayscaleJPEGs(struct foo * self)
{
	sqInt _return_value;

	_return_value = ((1) ? trueObject(self) : falseObject(self));
	if (!(failed(self))) {
		popthenPush(1, _return_value, self);
	}
	return null;
}


/*	Note: This is coded so that it can be run in Squeak. */

	/* InterpreterPlugin>>#setInterpreter: */
EXPORT(sqInt)
setInterpreter(struct VirtualMachine *anInterpreter)
{
	sqInt ok;

	interpreterProxy = anInterpreter;
	ok = ((interpreterProxy->majorVersion()) == (VM_PROXY_MAJOR))
	 && ((interpreterProxy->minorVersion()) >= (VM_PROXY_MINOR));
	if (ok) {
		
#if !defined(SQUEAK_BUILTIN_PLUGIN)
		booleanValueOf = interpreterProxy->booleanValueOf;
		byteSizeOf = interpreterProxy->byteSizeOf;
		failed = interpreterProxy->failed;
		falseObject = interpreterProxy->falseObject;
		fetchIntegerofObject = interpreterProxy->fetchIntegerofObject;
		fetchPointerofObject = interpreterProxy->fetchPointerofObject;
		firstIndexableField = interpreterProxy->firstIndexableField;
		integerObjectOf = interpreterProxy->integerObjectOf;
		isKindOf = interpreterProxy->isKindOf;
#if VM_PROXY_MAJOR > 1 || (VM_PROXY_MAJOR == 1 && VM_PROXY_MINOR >= 15)
		isBooleanObject = interpreterProxy->isBooleanObject;
#else
#if !defined(isBooleanObject)
		isBooleanObject = 0;
#endif
#endif
		isBytes = interpreterProxy->isBytes;
		isIntegerObject = interpreterProxy->isIntegerObject;
		isWordsOrBytes = interpreterProxy->isWordsOrBytes;
		pop = interpreterProxy->pop;
		popthenPush = interpreterProxy->popthenPush;
		primitiveFail = interpreterProxy->primitiveFail;
		primitiveFailFor = interpreterProxy->primitiveFailFor;
		stSizeOf = interpreterProxy->stSizeOf;
		stackIntegerValue = interpreterProxy->stackIntegerValue;
		stackValue = interpreterProxy->stackValue;
		success = interpreterProxy->success;
		trueObject = interpreterProxy->trueObject;
#endif /* !defined(SQUEAK_BUILTIN_PLUGIN) */
	}
	return ok;
}

	/* SmartSyntaxInterpreterPlugin>>#sqAssert: */
static sqInt
sqAssert(sqInt aBool, struct foo * self)
{
	/* missing DebugCode */;
	return aBool;
}


#ifdef SQUEAK_BUILTIN_PLUGIN

static char _m[] = "JPEGReadWriter2Plugin";
void* JPEGReadWriter2Plugin_exports[][3] = {
	{(void*)_m, "getModuleName", (void*)getModuleName},
	{(void*)_m, "primImageHeight\000\377", (void*)primImageHeight},
	{(void*)_m, "primImageNumComponents\000\377", (void*)primImageNumComponents},
	{(void*)_m, "primImageWidth\000\377", (void*)primImageWidth},
	{(void*)_m, "primJPEGCompressStructSize\000\377", (void*)primJPEGCompressStructSize},
	{(void*)_m, "primJPEGDecompressStructSize\000\377", (void*)primJPEGDecompressStructSize},
	{(void*)_m, "primJPEGErrorMgr2StructSize\000\377", (void*)primJPEGErrorMgr2StructSize},
	{(void*)_m, "primJPEGPluginIsPresent\000\377", (void*)primJPEGPluginIsPresent},
	{(void*)_m, "primJPEGReadHeaderfromByteArrayerrorMgr\000\377", (void*)primJPEGReadHeaderfromByteArrayerrorMgr},
	{(void*)_m, "primJPEGReadImagefromByteArrayonFormdoDitheringerrorMgr\000\002", (void*)primJPEGReadImagefromByteArrayonFormdoDitheringerrorMgr},
	{(void*)_m, "primJPEGWriteImageonByteArrayformqualityprogressiveJPEGerrorMgr\000\002", (void*)primJPEGWriteImageonByteArrayformqualityprogressiveJPEGerrorMgr},
	{(void*)_m, "primSupports8BitGrayscaleJPEGs\000\377", (void*)primSupports8BitGrayscaleJPEGs},
	{(void*)_m, "setInterpreter", (void*)setInterpreter},
	{NULL, NULL, NULL}
};

#else /* ifdef SQ_BUILTIN_PLUGIN */

signed char primJPEGReadImagefromByteArrayonFormdoDitheringerrorMgrAccessorDepth = 2;
signed char primJPEGWriteImageonByteArrayformqualityprogressiveJPEGerrorMgrAccessorDepth = 2;

#endif /* ifdef SQ_BUILTIN_PLUGIN */
